development:
  adapter: postgresql
  encoding: unicode
  database: Test2
  pool: 5
  username: alok
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: Test2
  pool: 5
  username: alok
  password:

development:
  adapter: postgresql
  encoding: unicode
  database: Test2
  pool: 5
  username: alok
  password:
